server:
    port: 8081
spring:
  application:
    name: ShoppingCart
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678
